[pytest]
minversion = 8.0
addopts = -v -s --tb=short --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: швидкі базові перевірки критичної функціональності
    functional: детальні функціональні тести бізнес-логіки
    hw_6: для домашньої роботи #6 (HW-6)
    auth: тести аутентифікації та сесій
    alarm: тести сигналізації та реле
    distance: тести датчика відстані HC-SR04
    hw_9: для домашньої роботи #9 (HW-9)