[pytest]
minversion = 8.0
addopts = -v -s --tb=short --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto

markers =
    wifi: Wi-Fi functional tests (station_WiFi)
    ble: BLE tests (Bluedroid_GATT_Server)
    positive: positive test cases
    negative: negative test cases
    smoke: smoke test cases
